---
title: "P8105_hw3_jl6648"
output: github_document
author: Jixin Li
date: "2023-10-09"
---

# probelm 2 
```{r, message=FALSE}
library(tidyverse)
library(dplyr)
library(p8105.datasets)                                                                  # load the data
data("brfss_smart2010") 
```

```{r}
brfss_df =
  brfss_smart2010 |>
  janitor::clean_names() |>
  filter(topic == "Overall Health") |>
  separate(locationdesc, into = c("state", "county"), sep = " - ") |>
  filter(response == "Excellent" | response == "Very good" | response == "Good" | 
         response == "Fair" | response == "Poor") |>
  mutate(response = as.factor(response),
         response = ordered(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))) 
```

## question 1
In 2002, which states were observed at 7 or more locations? What about in 2010?
```{r}
prob1_q1_02 = filter(brfss_df, year == 2002) |>
  group_by(state) |>
  summarize(n_obs = n_distinct(county)) |>
  filter(n_obs >= 7) 

state_2002 = pull(prob1_q1_02, state)
```
In 2002, following states `r state_2002` were observed at 7 or more location

```{r}
prob1_q1_10 = filter(brfss_df, year == 2010) |>
  group_by(state) |>
  summarize(n_obs = n_distinct(county)) |>
  filter(n_obs >= 7) 

state_2010 = pull(prob1_q1_10, state)
```
In 2010, following states `r state_2010` were observed at 7 or more location

## question 2
```{r}
brfss_excellent =
brfss_df |>
  filter(response == "Excellent") |>
  select(year, state, county, response, data_value) |>
  group_by(year, state)

brfss_excellent |>
ggplot(aes(x = year, y = data_value)) +
  geom_line(aes(color = state)) +
  labs(
    title = "average value over time within a state",
    x = "Year",
    y = "average value",
    caption = "Data from the p8105.datasets package"
  ) 
```

## question 3
```{r}
brfss_NY =
  brfss_df |> 
  filter(state == "NY") |>
  filter(year == 2006 | year == 2010) |>
  select(year, state, county, response, data_value) |>
  group_by(year, state)

brfss_NY |>
ggplot(aes(x = year, y = data_value)) +
  geom_line(aes(color = county)) +
  labs(
    title = "average value among locations in NY states in 2006 and 2010",
    x = "Year",
    y = "average value",
    caption = "Data from the p8105.datasets package"
  ) 
```

# problem 3
```{r}
covar_df =
  read_csv("nhanes_covar.csv") |>
  janitor::clean_names() |>
  filter(age >= 21) |>
   mutate(                                  
    sex = replace(sex, sex == 2, "Female"),
    sex = replace(sex, sex == 1, "Male"),
    education = replace(education, education == 1, "Less than high school"),
    education = replace(education, education == 2, "High school equivalent"),
    education = replace(education, education == 3, "More than high school")
   ) |>
  mutate(sex = as.factor(sex),
         education = as.factor(education)
  )
```

```{r}
accel_df =
  read_csv("nhanes_accel.csv") |>
  janitor::clean_names()
```

```{r}
combine_df =
  inner_join(covar_df, accel_df, by = "seqn")
```

